/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.StudentBLL;
import BLL.StudentGradeBLL;
import DAL.CourseDAL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StudentGradeGUI extends javax.swing.JInternalFrame {

    private List<String> courses = new ArrayList<>();
    private List<String> students = new ArrayList<>();
    StudentGradeBLL studentGradeBLL = new StudentGradeBLL();
    private boolean insert = false;

    /**
     * Creates new form StudentGrade
     */
    public StudentGradeGUI() {
        initComponents();
        fillTable();
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);

        // Lấy danh sách khóa học từ CourseDAL
        CourseDAL courseDAL = new CourseDAL();
        courses = courseDAL.getCourseIDs();

        StudentBLL studentBLL = new StudentBLL();
        students = studentBLL.getStudentIDs();

        // Đưa danh sách khóa học vào JComboBox
        for (String course : courses) {
            cbMaKhoaHoc.addItem(course);
        }
//        txtPersonID.setEditable(false);

        for (String student : students) {
            cbMaSV.addItem(student);
        }
        cbMaKhoaHoc.setSelectedItem(null);
        cbMaSV.setSelectedItem(null);
    }

    private void fillTable() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);

        resetValue();

        // Gọi phương thức đọc sinh viên từ BLL
        List<List<Object>> studentGradeList = studentGradeBLL.readStudent();

        // Duyệt qua danh sách và thêm dữ liệu vào bảng
        for (List<Object> studentGradeInfo : studentGradeList) {
            tableModel.addRow(studentGradeInfo.toArray());
        }
    }

    private void resetValue() {
        cbMaKhoaHoc.setSelectedItem(null);
        cbMaSV.setSelectedItem(null);
        txtTenKhoaHoc.setText("");
        txtTenSV.setText("");
        txtDiemSo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtTenKhoaHoc = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiemSo = new javax.swing.JTextField();
        cbMaKhoaHoc = new javax.swing.JComboBox<>();
        cbMaSV = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Tên sinh viên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 82, 24));

        txtTenKhoaHoc.setEditable(false);
        txtTenKhoaHoc.setEnabled(false);
        getContentPane().add(txtTenKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 310, -1));

        txtTenSV.setEditable(false);
        txtTenSV.setEnabled(false);
        getContentPane().add(txtTenSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 310, -1));

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ KẾT QUẢ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 218, 55));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel2.setText("Mã khóa học:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 82, 22));
        getContentPane().add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 200, -1));

        jLabel3.setText("Mã sinh viên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 82, 24));

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 90, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã khóa học", "Mã sinh viên", "Điểm số", "Tên sinh viên", "Tên khóa học"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 253, 720, 230));

        jLabel4.setText("Tên khóa học:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 82, 22));

        jLabel6.setText("Điểm số:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 82, 24));
        getContentPane().add(txtDiemSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, -1));

        getContentPane().add(cbMaKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 162, -1));

        getContentPane().add(cbMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 162, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có muốn cập thay đổi quả học tập không?", "Question", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION) {
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            btnLuu.setVisible(true);
            btnHuy.setVisible(true);
        } else {
            System.out.println("Người dùng đã chọn Không");

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchQuery = jtfSearch.getText().trim();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);

        if (!searchQuery.isEmpty()) {
            List<List<Object>> searchResult = studentGradeBLL.searchStudentGrade(searchQuery);

            if (searchResult != null) {
                // Xóa dữ liệu cũ trong bảng
                tableModel.setRowCount(0);

                // Hiển thị kết quả tìm kiếm trên bảng
                for (List<Object> studentGradeInfo : searchResult) {
                    tableModel.addRow(studentGradeInfo.toArray());
                }
            }
        } else {
            // Nếu trường tìm kiếm trống, hiển thị tất cả sinh viên
            fillTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        btnThem.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);

    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra xem có hàng được chọn không
            int enrollmentID = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

            // Xác nhận từ người dùng
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                // Người dùng đã xác nhận muốn xóa
                boolean success = studentGradeBLL.deleteStudentGrade(enrollmentID);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    fillTable(); // Cập nhật lại bảng jtStudentGrade
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công.");
                }
            } else {
                // Người dùng đã chọn NO hoặc đóng hộp thoại, không thực hiện xóa.
                JOptionPane.showMessageDialog(this, "Xóa đã bị hủy.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn kết quả học tập muốn xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Lấy hàng được chọn
        int selectedRow = jTable1.getSelectedRow();

        // Kiểm tra xem có hàng nào được chọn hay không
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng và hiển thị lên giao diện
            int courseID = Integer.parseInt(jTable1.getValueAt(selectedRow, 1).toString());
            int studentID = Integer.parseInt(jTable1.getValueAt(selectedRow, 2).toString());
            String grade = jTable1.getValueAt(selectedRow, 3).toString();
            String studentName = jTable1.getValueAt(selectedRow, 4).toString();
            String courseName = jTable1.getValueAt(selectedRow, 5).toString();

            // Hiển thị dữ liệu lên giao diện
            cbMaKhoaHoc.setSelectedItem(String.valueOf(courseID));
            cbMaSV.setSelectedItem(String.valueOf(studentID));
            txtTenKhoaHoc.setText(courseName);
            txtTenSV.setText(studentName);
            txtDiemSo.setText(grade);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm kết quả học tập không?", "Question", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION) {
            insert = true;
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            btnLuu.setVisible(true);
            btnHuy.setVisible(true);

        } else {
            System.out.println("Người dùng đã chọn Không");

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        resetValue();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // Lấy dữ liệu được chọn từ bảng
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy dữ liệu ban đầu

            int courseID = Integer.parseInt(jTable1.getValueAt(selectedRow, 1).toString());
            int studentID = Integer.parseInt(jTable1.getValueAt(selectedRow, 2).toString());
            float grade = Float.parseFloat(jTable1.getValueAt(selectedRow, 3).toString());

            // Lấy dữ liệu mới từ giao diện
            int newCourseID;
            int newStudentID;
            float newGrade;

            try {
                newCourseID = Integer.parseInt(cbMaKhoaHoc.getSelectedItem().toString());
                newStudentID = Integer.parseInt(cbMaSV.getSelectedItem().toString());
                newGrade = Float.parseFloat(txtDiemSo.getText());

                // Kiểm tra điểm số phải lớn hơn hoặc bằng 0 và bé hơn 4
                if (newGrade < 0 || newGrade >= 4) {
                    JOptionPane.showMessageDialog(this, "Điểm số phải lớn hơn hoặc bằng 0 và bé hơn 4.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số cho mã khóa học, mã sinh viên, và điểm số.");
                return;
            }

            // Kiểm tra xem có sự thay đổi không
            if (courseID != newCourseID || studentID != newStudentID || grade != newGrade) {
                // Nếu có sự thay đổi, thực hiện cập nhật dữ liệu
                if (insert) {
                    // Thực hiện thêm dữ liệu mới vào cơ sở dữ liệu
                    int enrollmentID = studentGradeBLL.insertStudentGrade(newCourseID, newStudentID, newGrade);

                    if (enrollmentID > 0) {
                        // Hiển thị thông báo khi thêm dữ liệu thành công
                        JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công.");

                        // Cập nhật lại bảng hiển thị danh sách sinh viên
                        fillTable();
                        resetValue();
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm dữ liệu thất bại.");
                    }
                } else {
                    int enrollmentID = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                    boolean success = studentGradeBLL.editStudentGrade(enrollmentID, newCourseID, newStudentID, newGrade);
                    if (success) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công.");
                        // Sau khi cập nhật thành công, làm mới bảng
                        fillTable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại.");
                    }
                }
                btnHuy.setVisible(false);
                btnLuu.setVisible(false);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
                insert = false;
            } else {
                // Nếu không có sự thay đổi, hiển thị thông báo "Không có sự thay đổi!"
                JOptionPane.showMessageDialog(this, "Không có sự thay đổi!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMaKhoaHoc;
    private javax.swing.JComboBox<String> cbMaSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField txtDiemSo;
    private javax.swing.JTextField txtTenKhoaHoc;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
