/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BLL.CourseBLL;
import BLL.DepartmentBLL;
import BLL.OnlineCourseBLL;
import BLL.OnsiteCourseBLL;
import DTO.Course;
import DTO.Department;
import DTO.OnlineCourse;
import DTO.OnsiteCourse;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;


/**
 *
 * @author Admin
 */
public class CourseInsert_Edit extends javax.swing.JFrame {
    CourseBLL courseBLL=new CourseBLL();
    OnlineCourseBLL onlineBLL=new OnlineCourseBLL();
    OnsiteCourseBLL onsiteBLL=new OnsiteCourseBLL();
    DepartmentBLL departmentBLL = new DepartmentBLL();
    boolean insert = true;
    boolean flag = false;
    
    /**
     * Creates new form Form
     */
    public CourseInsert_Edit() {
        initComponents();
        this.jComboBox2.addItem("");
        for(int x: courseBLL.getListDepartmentId()){
            String data= Integer.toString(x);
            this.jComboBox2.addItem(data);
        }
    }

    public boolean isInsert() {
        return insert;
    }

    public void setInsert(boolean insert) {
        this.insert = insert;
    }

    public boolean isFlag() {
        return flag;
    }

    public void setFlag(boolean flag) {
        this.flag = flag;
    }

    public JComboBox<String> getjComboBox2() {
        return jComboBox2;
    }

    public void setjComboBox2(JComboBox<String> jComboBox2) {
        this.jComboBox2 = jComboBox2;
    }

    public JTextField getjTextFieldGia() {
        return jTextFieldGia;
    }

    public void setjTextFieldGia(JTextField jTextFieldGia) {
        this.jTextFieldGia = jTextFieldGia;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JTextField getjTextFieldNgay() {
        return jTextFieldNgay;
    }

    public void setjTextFieldNgay(JTextField jTextFieldNgay) {
        this.jTextFieldNgay = jTextFieldNgay;
    }

    public JTextField getjTextFieldDiaChi() {
        return jTextFieldDiaChi;
    }

    public void setjTextFieldDiaChi(JTextField jTextFieldDiaChi) {
        this.jTextFieldDiaChi = jTextFieldDiaChi;
    }

    public JTextField getjTextFieldGio() {
        return jTextFieldGio;
    }

    public void setjTextFieldGio(JTextField jTextFieldGio) {
        this.jTextFieldGio = jTextFieldGio;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    public JTextField getjTextFieldTen() {
        return jTextFieldTen;
    }

    public void setjTextFieldTen(JTextField jTextFieldTen) {
        this.jTextFieldTen = jTextFieldTen;
    }

    public JTextField getjTextFieldUrl() {
        return jTextFieldUrl;
    }

    public void setjTextFieldUrl(JTextField jTextFieldUrl) {
        this.jTextFieldUrl = jTextFieldUrl;
    }
    
    public void Clear() {
        jTextFieldDiaChi.setText("");
        jTextFieldGia.setText("");
        jTextFieldGio.setText("");
        jTextFieldId.setText("");
        jTextFieldNgay.setText("");
        jTextFieldTen.setText("");
        jTextFieldUrl.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGia = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jTextFieldNgay = new javax.swing.JTextField();
        jTextFieldGio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin khóa học");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 6, 223, 34));

        jLabel2.setText("Mã khóa học");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, 70, 19));

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 112, 127, 25));

        jLabel3.setText("Tên khóa học");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, -1, 19));
        getContentPane().add(jTextFieldTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 149, 127, 25));

        jLabel4.setText("Giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, 70, 20));
        getContentPane().add(jTextFieldGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 185, 126, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trực tuyến", "Tại lớp" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 75, 127, 25));

        jLabel5.setText("Khóa học");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 70, 19));

        jLabel6.setText("URL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 78, 37, 19));

        jLabel7.setText("Địa chỉ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 115, 49, 19));

        jLabel8.setText("Ngày");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 152, 37, -1));

        jLabel9.setText("Giờ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 188, 37, -1));
        getContentPane().add(jTextFieldUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 75, 265, 25));
        getContentPane().add(jTextFieldDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 112, 265, 25));
        getContentPane().add(jTextFieldNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 149, 170, -1));

        jTextFieldGio.setToolTipText("");
        getContentPane().add(jTextFieldGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 185, 170, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Hoàn thành");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 271, 117, 31));

        jLabel10.setText("Mã phòng");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 223, 62, 26));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 225, 128, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(flag == true) {
                if(insert == true) {
                    Course course = new Course();
                    course.setTitle(jTextFieldTen.getText());
                    if(!jTextFieldGia.getText().isEmpty()) {
                        course.setCredits(Integer.parseInt(jTextFieldGia.getText()));
                    }
                    for(Department x: departmentBLL.getListDepartment()) {
                        if(x.getName().equals(jComboBox2.getSelectedItem().toString())) {
                            course.setDepartmentId(x.getDepartmentId());
                        }
                    }
                    if(courseBLL.addCourse(course) != 0) {
                        if(jComboBox1.getSelectedIndex() == 0) {                       
                            OnlineCourse online = new OnlineCourse();
                            online.setCourseId(courseBLL.getLastCourseId());
                            online.setUrl(jTextFieldUrl.getText());
                            if(onlineBLL.addCourse(online) != 0) {
                                JOptionPane.showMessageDialog(null, "Added course successfully!");
                                Clear();
                            }
                        }
                        else {
                            OnsiteCourse onsite = new OnsiteCourse();
                            onsite.setCourseId(courseBLL.getLastCourseId());
                            onsite.setLocation(jTextFieldDiaChi.getText());
                            onsite.setDays(jTextFieldNgay.getText());
                            onsite.setTime(jTextFieldGio.getText());
                            if(onsiteBLL.addCourse(onsite) != 0) {
                                JOptionPane.showMessageDialog(null, "Added course successfully!");
                                Clear();
                            }
                        }
                    }
                    
                }
                else {
                    Course course = new Course();
                    course.setCourseId(Integer.parseInt(jTextFieldId.getText()));
                    course.setTitle(jTextFieldTen.getText());
                    if(!jTextFieldGia.getText().isEmpty()) {
                        course.setCredits(Integer.parseInt(jTextFieldGia.getText()));
                    }
                    for(Department x: departmentBLL.getListDepartment()) {
                        if(x.getName().equals(jComboBox2.getSelectedItem().toString())) {
                            course.setDepartmentId(x.getDepartmentId());
                        }
                    }
                    if(courseBLL.updateCourse(course) != 0) {
                        if(jComboBox1.getSelectedIndex() == 0) {                       
                            OnlineCourse online = new OnlineCourse();
                            online.setCourseId(Integer.parseInt(jTextFieldId.getText()));
                            online.setUrl(jTextFieldUrl.getText());
                            if(onlineBLL.updateCourse(online) != 0) {
                                JOptionPane.showMessageDialog(null, "Edited the course successfully !");
                                Clear();
                                dispose();
                            }
                        }
                        else {
                            OnsiteCourse onsite = new OnsiteCourse();
                            onsite.setCourseId(Integer.parseInt(jTextFieldId.getText()));
                            onsite.setLocation(jTextFieldDiaChi.getText());
                            onsite.setDays(jTextFieldNgay.getText());
                            onsite.setTime(jTextFieldGio.getText());
                            if(onsiteBLL.updateCourse(onsite) != 0) {
                                JOptionPane.showMessageDialog(null, "Edited the course successfully !");
                                Clear();
                                dispose();
                            }
                        } 
                    } 
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CourseInsert_Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(flag == true) {
            jTextFieldUrl.setText("");
            jTextFieldDiaChi.setText("");
            jTextFieldNgay.setText("");
            jTextFieldGio.setText(""); 
            if(jComboBox1.getSelectedIndex() == 0) {
                jTextFieldUrl.setEnabled(true);
                jTextFieldDiaChi.setEnabled(false);
                jTextFieldNgay.setEnabled(false);
                jTextFieldGio.setEnabled(false);          
            }
            else {
                jTextFieldUrl.setEnabled(false);
                jTextFieldDiaChi.setEnabled(true);
                jTextFieldNgay.setEnabled(true);
                jTextFieldGio.setEnabled(true); 
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseInsert_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseInsert_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseInsert_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseInsert_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseInsert_Edit().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldGia;
    private javax.swing.JTextField jTextFieldGio;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNgay;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
